/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demoapriltag;

import edu.wpi.first.cameraserver.CameraServer;
import edu.wpi.first.cscore.CvSink;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       CameraServer.startAutomaticCapture();

       CvSink cvSink = CameraServer.getVideo();

       while(true) {
        try {
            Thread.sleep(100);
        } catch(InterruptedException e) {
            e.printStackTrace();
        }
       }
    }
}
